development:
  adapter: postgresql
  encoding: unicode
  database: AddressBook
  pool: 5
  host: localhost
  username: postgres
  password: Ginger111

test:
  adapter: postgresql
  encoding: unicode
  database: AddressBookTest
  pool: 5
  username: postgres
  password: Ginger111

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>